language: c # defaults to ruby
install:
  - sudo apt-get install ksh zsh -y
before_script:
  - curl -o /tmp/urchin https://raw.github.com/scraperwiki/urchin/master/urchin && chmod +x /tmp/urchin
script:
#  - NVM_DIR=$TRAVIS_BUILD_DIR make URCHIN=/tmp/urchin test
#  - $SHELL -c "printf '\n\033[0;34m%s\033[0m\n' \"Running tests in $0\"; NVM_DIR=$TRAVIS_BUILD_DIR /tmp/urchin -f test/$TEST_SUITE"
  - NVM_DIR=$TRAVIS_BUILD_DIR make URCHIN=/tmp/urchin fast2
env:
  - SHELL=sh TEST_SUITE=fast
  - SHELL=dash TEST_SUITE=fast
  - SHELL=bash TEST_SUITE=fast
  - SHELL=zsh TEST_SUITE=fast
  - SHELL=ksh TEST_SUITE=fast
#  - SHELL=bash TEST_SUITE=slow

